# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QRvD5yfErLDwoqXalN8Po5Z8GlEJ0sfn
"""

print("hello world!")



True
1
False
0

minha_tupla = (1, 2, 3, 4, 5)
primeiro_elemento = minha_tupla[0]
print(primeiro_elemento)

numero = int(input("Digite um dado: "))
manipular  = numero * 20
manipular2 = numero + 15
manipular3 = numero / 2
print("Resultado:",manipular) # Concatenar == Juntar
print(manipular2)
print(manipular3)
print(numero)
Calculo = manipular / manipular3
# Concatenar == Juntar
print("Valor:", Calculo)
print("Resultado:"+"",Calculo)
print('Resultado: {}' .format(Calculo))
print('Resultado: %d'%(Calculo))
print(f'Resultado: {Calculo}')

"""1 - CRIE UM CALCULADORA SÓ COM INPUT() E PRINT() VARIÁVEIS"""

print('Calculadora das 4 operações: ')
n1 =  float(input('>>'))
n2 =  float(input('>>'))

soma =  n1 + n2
sub =  n1 - n2
div =  n1 / n2
mult =  n1 * n2

vericar1 =  soma% 2 == 0
vericar2 =  sub % 2 == 0
vericar3 =  div % 2 == 0
vericar4 =  mult% 2 == 0

print(f'''
RESULTADOS:
SOMA  -  {soma} é par ? = {vericar1}
SUBTRAÇÃO  - {sub} é par ? = {vericar2}
MULTIPLICAÇÃO - {mult} é par ? = {vericar3}
DIVISÃO - {div} é par ? = {vericar4}
''')

"""Listas em Python"""

lista = [2, 3, 4, 5, 6]
print(lista[0]) #achar um item na lista por meio do seu índice
print(lista)
tamanho = len(lista)
print(tamanho)